-- ==============================================================================
-- 02_raw_schema.sql
-- RAW Schema DDL & Ingestion Definitions
-- Tables: CUSTOMERS, CUSTOMER_EVENTS
-- ==============================================================================

USE DATABASE CUSTOMER_CHURN_DB;
USE SCHEMA RAW;

-- 1. Raw Customers Landing Table
CREATE TABLE IF NOT EXISTS CUSTOMERS (
    CUSTOMER_ID         VARCHAR(64) PRIMARY KEY,
    GENDER              VARCHAR(16),
    SENIOR_CITIZEN      NUMBER(38, 0),
    PARTNER             VARCHAR(8),
    DEPENDENTS          VARCHAR(8),
    TENURE              NUMBER(38, 0),
    PHONE_SERVICE       VARCHAR(8),
    MULTIPLE_LINES      VARCHAR(32),
    INTERNET_SERVICE    VARCHAR(32),
    ONLINE_SECURITY     VARCHAR(32),
    ONLINE_BACKUP       VARCHAR(32),
    DEVICE_PROTECTION   VARCHAR(32),
    TECH_SUPPORT        VARCHAR(32),
    STREAMING_TV        VARCHAR(32),
    STREAMING_MOVIES    VARCHAR(32),
    CONTRACT            VARCHAR(32),
    PAPERLESS_BILLING   VARCHAR(8),
    PAYMENT_METHOD      VARCHAR(64),
    MONTHLY_CHARGES     FLOAT,
    TOTAL_CHARGES       FLOAT,
    CHURN_LABEL         VARCHAR(8),
    _INGESTED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_FILENAME    VARCHAR(256) DEFAULT 'telco_customer_churn.csv'
);

-- 2. Raw Customer Events Landing Table (Simulated Real-Time Streams)
CREATE TABLE IF NOT EXISTS CUSTOMER_EVENTS (
    EVENT_ID            VARCHAR(64) DEFAULT UUID_STRING() PRIMARY KEY,
    CUSTOMER_ID         VARCHAR(64) NOT NULL,
    EVENT_TYPE          VARCHAR(64) NOT NULL,
    EVENT_TIMESTAMP     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    EVENT_VALUE         FLOAT DEFAULT 1.0,
    EVENT_PAYLOAD       VARIANT,
    IS_SIMULATED        BOOLEAN DEFAULT TRUE,
    _INGESTED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 3. Staging and Copy Commands
-- Example: Load CSV from named stage RAW_STAGE
-- COPY INTO CUSTOMERS (
--     CUSTOMER_ID, GENDER, SENIOR_CITIZEN, PARTNER, DEPENDENTS, TENURE,
--     PHONE_SERVICE, MULTIPLE_LINES, INTERNET_SERVICE, ONLINE_SECURITY,
--     ONLINE_BACKUP, DEVICE_PROTECTION, TECH_SUPPORT, STREAMING_TV,
--     STREAMING_MOVIES, CONTRACT, PAPERLESS_BILLING, PAYMENT_METHOD,
--     MONTHLY_CHARGES, TOTAL_CHARGES, CHURN_LABEL
-- )
-- FROM @RAW_STAGE/telco_customer_churn.csv
-- FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT)
-- ON_ERROR = 'CONTINUE';

-- 4. Ingestion Validation Query
SELECT
    COUNT(*) AS TOTAL_RAW_CUSTOMERS,
    COUNT(DISTINCT CUSTOMER_ID) AS DISTINCT_CUSTOMERS,
    SUM(CASE WHEN CHURN_LABEL = 'Yes' THEN 1 ELSE 0 END) AS HISTORICAL_CHURNED,
    ROUND(AVG(MONTHLY_CHARGES), 2) AS AVG_MONTHLY_CHARGES
FROM CUSTOMERS;
