-- ==============================================================================
-- 03_analytics_schema.sql
-- ANALYTICS Schema DDL & Analytical Views
-- Tables: CUSTOMER_FEATURES
-- Views: V_CUSTOMER_360, V_RFM_METRICS, V_CHURN_CORRELATIONS
-- ==============================================================================

USE DATABASE CUSTOMER_CHURN_DB;
USE SCHEMA ANALYTICS;

-- 1. Silver / Analytics Feature Store Table
CREATE TABLE IF NOT EXISTS CUSTOMER_FEATURES (
    CUSTOMER_ID                 VARCHAR(64) PRIMARY KEY,
    TENURE                      NUMBER(38, 0),
    TENURE_COHORT               VARCHAR(32),
    CONTRACT                    VARCHAR(32),
    CONTRACT_RISK_INDEX         NUMBER(38, 0),
    PAYMENT_METHOD              VARCHAR(64),
    IS_HIGH_RISK_PAYMENT        NUMBER(38, 0),
    INTERNET_SERVICE            VARCHAR(32),
    IS_FIBER_WITHOUT_TECHSUPPORT NUMBER(38, 0),
    MONTHLY_CHARGES             FLOAT,
    TOTAL_CHARGES               FLOAT,
    AVG_MONTHLY_CHARGES_HISTORY FLOAT,
    CHARGE_DISCREPANCY          FLOAT,
    CHARGE_RATIO                FLOAT,
    SECURITY_BUNDLE_SCORE       NUMBER(38, 0),
    STREAMING_BUNDLE_SCORE      NUMBER(38, 0),
    TOTAL_ACTIVE_SERVICES       NUMBER(38, 0),
    COMPLAINT_COUNT             NUMBER(38, 0) DEFAULT 0,
    SUPPORT_TICKET_COUNT        NUMBER(38, 0) DEFAULT 0,
    PAYMENT_FAILED_COUNT        NUMBER(38, 0) DEFAULT 0,
    LOGIN_COUNT                 NUMBER(38, 0) DEFAULT 0,
    RECENT_EVENTS_COUNT         NUMBER(38, 0) DEFAULT 0,
    ESTIMATED_CLV               FLOAT,
    FEATURE_SNAPSHOT_TS         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 2. Customer 360 View: Unified View combining Demographics, Features, and Raw Metadata
CREATE OR REPLACE VIEW V_CUSTOMER_360 AS
SELECT
    c.CUSTOMER_ID,
    c.GENDER,
    c.SENIOR_CITIZEN,
    c.PARTNER,
    c.DEPENDENTS,
    c.TENURE,
    f.TENURE_COHORT,
    c.CONTRACT,
    f.CONTRACT_RISK_INDEX,
    c.PAYMENT_METHOD,
    f.IS_HIGH_RISK_PAYMENT,
    c.INTERNET_SERVICE,
    f.IS_FIBER_WITHOUT_TECHSUPPORT,
    c.MONTHLY_CHARGES,
    c.TOTAL_CHARGES,
    f.CHARGE_RATIO,
    f.SECURITY_BUNDLE_SCORE,
    f.STREAMING_BUNDLE_SCORE,
    f.TOTAL_ACTIVE_SERVICES,
    f.COMPLAINT_COUNT,
    f.SUPPORT_TICKET_COUNT,
    f.PAYMENT_FAILED_COUNT,
    f.ESTIMATED_CLV,
    c.CHURN_LABEL
FROM CUSTOMER_CHURN_DB.RAW.CUSTOMERS c
LEFT JOIN CUSTOMER_CHURN_DB.ANALYTICS.CUSTOMER_FEATURES f
    ON c.CUSTOMER_ID = f.CUSTOMER_ID;

-- 3. RFM Metrics View (Recency, Frequency, Monetary Value)
CREATE OR REPLACE VIEW V_RFM_METRICS AS
SELECT
    f.CUSTOMER_ID,
    f.TENURE AS MONETARY_TENURE_MONTHS,
    f.TOTAL_CHARGES AS CUMULATIVE_SPEND,
    f.MONTHLY_CHARGES AS CURRENT_MRR,
    f.TOTAL_ACTIVE_SERVICES AS SERVICE_FREQUENCY,
    f.RECENT_EVENTS_COUNT AS ACTIVITY_FREQUENCY,
    f.COMPLAINT_COUNT AS RISK_FREQUENCY,
    NTILE(5) OVER (ORDER BY f.TOTAL_CHARGES DESC) AS MONETARY_QUINTILE,
    NTILE(5) OVER (ORDER BY f.TENURE DESC) AS RECENCY_QUINTILE,
    NTILE(5) OVER (ORDER BY f.TOTAL_ACTIVE_SERVICES DESC) AS FREQUENCY_QUINTILE
FROM CUSTOMER_CHURN_DB.ANALYTICS.CUSTOMER_FEATURES f;

-- 4. Churn Correlation Analysis by Contract & Payment Method
CREATE OR REPLACE VIEW V_CHURN_CORRELATIONS AS
SELECT
    CONTRACT,
    PAYMENT_METHOD,
    INTERNET_SERVICE,
    COUNT(*) AS TOTAL_CUSTOMERS,
    SUM(CASE WHEN CHURN_LABEL = 'Yes' THEN 1 ELSE 0 END) AS CHURNED_CUSTOMERS,
    ROUND(SUM(CASE WHEN CHURN_LABEL = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS CHURN_PERCENTAGE,
    ROUND(AVG(MONTHLY_CHARGES), 2) AS AVG_MONTHLY_CHARGES,
    ROUND(AVG(TOTAL_CHARGES), 2) AS AVG_TOTAL_CHARGES
FROM CUSTOMER_CHURN_DB.RAW.CUSTOMERS
GROUP BY CONTRACT, PAYMENT_METHOD, INTERNET_SERVICE;
