-- ==============================================================================
-- 04_ml_schema.sql
-- ML Schema DDL & Model Registry Tables
-- Tables: CHURN_PREDICTIONS, MODEL_RUNS
-- Views: V_HIGH_RISK_CUSTOMERS, V_MODEL_PERFORMANCE_METRICS
-- ==============================================================================

USE DATABASE CUSTOMER_CHURN_DB;
USE SCHEMA ML;

-- 1. Churn Predictions Table
CREATE TABLE IF NOT EXISTS CHURN_PREDICTIONS (
    PREDICTION_ID           VARCHAR(64) DEFAULT UUID_STRING() PRIMARY KEY,
    CUSTOMER_ID             VARCHAR(64) NOT NULL,
    CHURN_PROBABILITY       FLOAT NOT NULL,
    RISK_LEVEL              VARCHAR(16) NOT NULL, -- LOW, MEDIUM, HIGH, CRITICAL
    ESTIMATED_CLV           FLOAT,
    REVENUE_AT_RISK         FLOAT,
    TOP_DRIVERS             VARIANT,             -- JSON Array of SHAP top drivers
    MODEL_VERSION           VARCHAR(64) NOT NULL,
    PREDICTION_LATENCY_MS   FLOAT,
    PREDICTION_TIMESTAMP    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 2. Model Runs & MLOps Tracking Table
CREATE TABLE IF NOT EXISTS MODEL_RUNS (
    RUN_ID                  VARCHAR(64) PRIMARY KEY,
    MODEL_NAME              VARCHAR(64) NOT NULL,
    MODEL_VERSION           VARCHAR(64) NOT NULL,
    CALIBRATION_METHOD      VARCHAR(32),
    ROC_AUC                 FLOAT,
    PR_AUC                  FLOAT,
    F1_SCORE                FLOAT,
    PRECISION_SCORE         FLOAT,
    RECALL_SCORE            FLOAT,
    LOG_LOSS                FLOAT,
    BRIER_SCORE             FLOAT,
    HYPERPARAMETERS         VARIANT,
    DEPLOYMENT_STAGE        VARCHAR(32) DEFAULT 'Production',
    TRAINED_AT              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 3. High-Risk Customers Priority View
CREATE OR REPLACE VIEW V_HIGH_RISK_CUSTOMERS AS
SELECT
    p.CUSTOMER_ID,
    p.CHURN_PROBABILITY,
    p.RISK_LEVEL,
    p.REVENUE_AT_RISK,
    p.ESTIMATED_CLV,
    f.TENURE_COHORT,
    f.CONTRACT,
    f.MONTHLY_CHARGES,
    f.COMPLAINT_COUNT,
    f.SUPPORT_TICKET_COUNT,
    p.TOP_DRIVERS,
    p.MODEL_VERSION,
    p.PREDICTION_TIMESTAMP
FROM CUSTOMER_CHURN_DB.ML.CHURN_PREDICTIONS p
JOIN CUSTOMER_CHURN_DB.ANALYTICS.CUSTOMER_FEATURES f
    ON p.CUSTOMER_ID = f.CUSTOMER_ID
WHERE p.RISK_LEVEL IN ('HIGH', 'CRITICAL')
ORDER BY p.REVENUE_AT_RISK DESC;

-- 4. Model Performance Comparison View
CREATE OR REPLACE VIEW V_MODEL_PERFORMANCE_METRICS AS
SELECT
    MODEL_NAME,
    MODEL_VERSION,
    CALIBRATION_METHOD,
    DEPLOYMENT_STAGE,
    ROUND(ROC_AUC, 4) AS ROC_AUC,
    ROUND(PR_AUC, 4) AS PR_AUC,
    ROUND(F1_SCORE, 4) AS F1_SCORE,
    ROUND(RECALL_SCORE, 4) AS RECALL_SCORE,
    ROUND(PRECISION_SCORE, 4) AS PRECISION_SCORE,
    ROUND(BRIER_SCORE, 4) AS BRIER_SCORE,
    TRAINED_AT
FROM CUSTOMER_CHURN_DB.ML.MODEL_RUNS
ORDER BY ROC_AUC DESC;
