-- ==============================================================================
-- 05_reporting_schema.sql
-- REPORTING Schema DDL & Executive Action Tables
-- Tables: RETENTION_ACTIONS
-- Views: V_EXECUTIVE_CHURN_SUMMARY, V_REVENUE_AT_RISK_BY_SEGMENT, V_RETENTION_CAMPAIGN_ROI
-- ==============================================================================

USE DATABASE CUSTOMER_CHURN_DB;
USE SCHEMA REPORTING;

-- 1. Retention Actions Decision Table
CREATE TABLE IF NOT EXISTS RETENTION_ACTIONS (
    ACTION_ID                   VARCHAR(64) DEFAULT UUID_STRING() PRIMARY KEY,
    CUSTOMER_ID                 VARCHAR(64) NOT NULL,
    CHURN_PROBABILITY           FLOAT NOT NULL,
    RISK_LEVEL                  VARCHAR(16) NOT NULL,
    URGENCY                     VARCHAR(16) NOT NULL, -- IMMEDIATE, HIGH, MEDIUM, LOW
    RECOMMENDED_ACTION          VARCHAR(64) NOT NULL, -- VIP Concierge Call, Discount Offer, etc.
    REASON                      TEXT,
    REVENUE_AT_RISK             FLOAT,
    ESTIMATED_INTERVENTION_COST FLOAT,
    ESTIMATED_RETAINED_VALUE    FLOAT,
    ESTIMATED_NET_VALUE         FLOAT,
    ACTION_STATUS               VARCHAR(32) DEFAULT 'RECOMMENDED', -- RECOMMENDED, EXECUTED, REJECTED
    CREATED_AT                  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 2. Executive Churn & Financial Summary KPI View
CREATE OR REPLACE VIEW V_EXECUTIVE_CHURN_SUMMARY AS
SELECT
    COUNT(DISTINCT c.CUSTOMER_ID) AS TOTAL_CUSTOMERS,
    SUM(CASE WHEN p.RISK_LEVEL IN ('HIGH', 'CRITICAL') THEN 1 ELSE 0 END) AS AT_RISK_CUSTOMERS,
    ROUND(SUM(CASE WHEN p.RISK_LEVEL IN ('HIGH', 'CRITICAL') THEN 1 ELSE 0 END) * 100.0 / COUNT(DISTINCT c.CUSTOMER_ID), 2) AS AT_RISK_PERCENTAGE,
    ROUND(AVG(p.CHURN_PROBABILITY), 4) AS AVERAGE_CHURN_PROBABILITY,
    ROUND(SUM(p.REVENUE_AT_RISK), 2) AS TOTAL_REVENUE_AT_RISK,
    ROUND(SUM(r.ESTIMATED_NET_VALUE), 2) AS TOTAL_POTENTIAL_RECOVERY_VALUE,
    ROUND(SUM(c.MONTHLY_CHARGES), 2) AS TOTAL_MONTHLY_RECURRING_REVENUE
FROM CUSTOMER_CHURN_DB.RAW.CUSTOMERS c
LEFT JOIN CUSTOMER_CHURN_DB.ML.CHURN_PREDICTIONS p ON c.CUSTOMER_ID = p.CUSTOMER_ID
LEFT JOIN CUSTOMER_CHURN_DB.REPORTING.RETENTION_ACTIONS r ON c.CUSTOMER_ID = r.CUSTOMER_ID;

-- 3. Revenue at Risk by Customer Tenure & Contract Segment View
CREATE OR REPLACE VIEW V_REVENUE_AT_RISK_BY_SEGMENT AS
SELECT
    f.TENURE_COHORT,
    f.CONTRACT,
    f.PAYMENT_METHOD,
    COUNT(p.CUSTOMER_ID) AS CUSTOMER_COUNT,
    SUM(CASE WHEN p.RISK_LEVEL IN ('HIGH', 'CRITICAL') THEN 1 ELSE 0 END) AS HIGH_RISK_COUNT,
    ROUND(AVG(p.CHURN_PROBABILITY), 3) AS AVG_CHURN_PROB,
    ROUND(SUM(p.REVENUE_AT_RISK), 2) AS TOTAL_REVENUE_AT_RISK,
    ROUND(AVG(p.REVENUE_AT_RISK), 2) AS AVG_REVENUE_AT_RISK_PER_CUST
FROM CUSTOMER_CHURN_DB.ANALYTICS.CUSTOMER_FEATURES f
JOIN CUSTOMER_CHURN_DB.ML.CHURN_PREDICTIONS p ON f.CUSTOMER_ID = p.CUSTOMER_ID
GROUP BY f.TENURE_COHORT, f.CONTRACT, f.PAYMENT_METHOD
ORDER BY TOTAL_REVENUE_AT_RISK DESC;

-- 4. Retention Campaign ROI View
CREATE OR REPLACE VIEW V_RETENTION_CAMPAIGN_ROI AS
SELECT
    RECOMMENDED_ACTION,
    URGENCY,
    COUNT(*) AS TOTAL_RECOMMENDED_CAMPAIGNS,
    ROUND(SUM(REVENUE_AT_RISK), 2) AS TOTAL_REVENUE_PROTECTED,
    ROUND(SUM(ESTIMATED_INTERVENTION_COST), 2) AS TOTAL_INTERVENTION_INVESTMENT,
    ROUND(SUM(ESTIMATED_RETAINED_VALUE), 2) AS TOTAL_EXPECTED_RETAINED_VALUE,
    ROUND(SUM(ESTIMATED_NET_VALUE), 2) AS TOTAL_EXPECTED_NET_PROFIT,
    ROUND((SUM(ESTIMATED_NET_VALUE) / NULLIF(SUM(ESTIMATED_INTERVENTION_COST), 0)) * 100.0, 1) AS EXPECTED_CAMPAIGN_ROI_PERCENT
FROM CUSTOMER_CHURN_DB.REPORTING.RETENTION_ACTIONS
GROUP BY RECOMMENDED_ACTION, URGENCY
ORDER BY TOTAL_EXPECTED_NET_PROFIT DESC;

-- 5. Real-Time Churn Alert View (for Event-Triggered Interventions)
CREATE OR REPLACE VIEW V_REALTIME_CHURN_ALERTS AS
SELECT
    e.CUSTOMER_ID,
    e.EVENT_TYPE,
    e.EVENT_TIMESTAMP,
    p.CHURN_PROBABILITY AS CURRENT_CHURN_PROB,
    p.RISK_LEVEL,
    r.RECOMMENDED_ACTION,
    r.URGENCY
FROM CUSTOMER_CHURN_DB.RAW.CUSTOMER_EVENTS e
JOIN CUSTOMER_CHURN_DB.ML.CHURN_PREDICTIONS p ON e.CUSTOMER_ID = p.CUSTOMER_ID
JOIN CUSTOMER_CHURN_DB.REPORTING.RETENTION_ACTIONS r ON e.CUSTOMER_ID = r.CUSTOMER_ID
WHERE e.EVENT_TYPE IN ('complaint', 'payment_failed', 'cancellation_attempt')
  AND p.RISK_LEVEL IN ('HIGH', 'CRITICAL')
ORDER BY e.EVENT_TIMESTAMP DESC;
